### ISSUE TITLE
Sidebar widgets on a fresh WordPress installation

### ISSUE THREAD

**Issue by kreincke** [bootscore/bootscore#444] opened 2023-04-05 21:16 UTC
### Describe the bug

In version 5.3.2.3, the paddings of the sidebar units seem to be removed and their background colors are set to white. Additionally. the category color in the post header is lightened. In sum, these changings are a downgrade. But maybe it's a bug - I don't know.

Therefore I am going to ask: Is that modified behavior/appearance intended?

(Demoying screenshots are attached).

heartfully KR

### Steps to reproduce

* Install and activate WordPress 6.2 as delivered
* Install bootscore-main (5.2.3.3) in themes
* Install bootscore-child-main (latest) in themes
* Activate the bootscore-child theme
* Call the installed WordPress instance

### Screenshots and Additional Info

I've created 2 screenshots of that pure WordPress instance

* one with bootscore-5.2.3.2 (seems to be ok)
![bs-5 2 3 2-plus-wp-6 2](https://user-images.githubusercontent.com/1419632/230212314-4e49ab37-af8e-4852-855c-51aa43d71367.png)

* one with bootscore-5.2.3.3 (seems to be a bit ugly)
![bs-5 2 3 3-plus-wp-6 2](https://user-images.githubusercontent.com/1419632/230212471-9ca1e049-f014-4936-ad8b-24a375be0abf.png)

**Comment by crftwrk** [comment] 2023-04-06 08:07
No, it's not a bug.

As described in https://bootscore.me/blog/theme-blog/bootscore-5-2-3-3/, loop and sidebar has been refactored and uses `card-header` for title now.

You are using Gutenberg widgets which comes with a fresh WP installation. bootScore disables Gutenberg in widgets for several reasons. That's why you have to remove all widgets first and then readd them as described here https://bootscore.me/documentation/installation/#Theme-uploader.

**Comment by kreincke** [comment] 2023-04-06 09:41
Ok. A bit surprising. But reasonable. There's side effect: (bsfa) shortcuts do not work in the title. Is this also intended?

**Comment by kreincke** [comment] 2023-04-06 10:04
Is it possible to create the card and the card body if the title doesn't exist? We often want to place a message (eg. A picture) in the sidebar, that doesn't need a title but should look similar to the with titles? Or do we have to implement that by ourselves?
Br. Kr

**Comment by crftwrk** [comment] 2023-04-06 10:21
> There's side effect: (bsfa) shortcuts do not work in the title. Is this also intended?

It is possible that WP does not allow shortcodes in widget title. Try to add the `<i>...</i>` element instead

> Is it possible to create the card and the card body if the title doesn't exist?

`card` is there without title, but `card-body` depends on the title. You can try to improve this snippet. If you find a solution (without jS), we can improve this.
https://github.com/bootscore/bootscore/blob/9d1c42545210dc56a93d37a5a8b1ca8831b269e9/functions.php#L146-L156

**Comment by kreincke** [comment] 2023-04-06 19:46
I've understood your intentions and the challenge. Give me a bit of time. If I find a solution, I will come up with it.

Independent of that context this: Are you sure, that the registered code properly does what you want it to do? You are opening two divs, but do not close any div. Moreover: you are opening a section at the beginning and closing it at the end. But just before closing the section, you are opening a div. Does this not end up in an overlapping HTML tag structure?

**Comment by kreincke** [comment] 2023-04-08 08:06
I think I have a solution. Without any JS! 

But I do not understand how to activate it, without modifying an original bootscore file: Your code `register_sidebar(array(...` is embedded in the function `bootscore_widgets_init()` inside of `functions.php`. Any idea how to overwrite that function in my `functions.php` instead of commenting it out and inserting my variant in your `functions.php`?

heartfully KR

**Comment by crftwrk** [comment] 2023-04-08 10:14
You cannot override a single widget in your child. You have to override all by copy the whole 

```php
function bootscore_widgets_init() {
  ... 
add_action('widgets_init', 'bootscore_widgets_init');
```

to your child.

But if you have a better solution that fits to all users, you can create a PR and we merge it to main branch.

**Comment by kreincke** [comment] 2023-04-08 10:22
I had suspected it. So, I will implement it in this way. If it works to my satisfaction, I'll show you the effect on my site. If you are then satisfied, I will create the PR.

**Comment by crftwrk** [comment] 2023-04-08 10:31
Ok

**Comment by kreincke** [comment] 2023-04-09 10:23
Sorry for having to ask one more intermediate question. There is a tag in your code whose existence and form I do not understand:

 Your `register_sidebar` array opens the widget with `'before_widget' => '<section [...]>'` and closes it with `'after_widget'  => '<div></section>',`. What's the intended meaning of opening a new *div* before closing the *section* ?

First, I thought it's typo and that you wanted to close the div from `'after_title'   => '</h2><div class="card-body">'`. But if I improved the typo, the sidebar as a unit overlaps the footers. 

So this opening tag is somehow important. However, this structure implies that the number of not closed *divs* increases with the number of widgets. Even if you design the closing line like this: ` 'after_widget'  => '</div></section><div>'` (what works like your solution).

Please, can you explain the intended meaning of the opened *div* before the closed *\section*.

Many thanks for your patience KR

**Comment by crftwrk** [comment] 2023-04-09 17:12
The title `card-header` must be placed outside the `card-body`, [card docs](https://getbootstrap.com/docs/5.3/components/card/#header-and-footer). The `card-body` opens in `after_title` and closes in `after_widget`. That's why `card-body` is not created if widget has no title. Tricky...

```php
// Sidebar
register_sidebar(array(
  'name'          => esc_html__('Sidebar', 'bootscore'),
  'id'            => 'sidebar-1',
  'description'   => esc_html__('Add widgets here.', 'bootscore'),
  'before_widget' => '<section id="%1$s" class="widget %2$s card mb-4">', // card opens here
  'after_widget'  => '<div></section>', // card-body and card closes here
  'before_title'  => '<h2 class="widget-title card-header h5">',
  'after_title'   => '</h2><div class="card-body">', // card-body opens here
));
```

**Comment by justinkruit** [comment] 2023-04-09 20:00
This would honestly be great to fix by making custom blocks and use Gutenberg. But at the same time, I only develop blocks using ACF as the js way is quite difficult...

**Comment by kreincke** [comment] 2023-04-10 06:53
Sorry, have a look at these lines:

`'after_title'   => '</h2><div class="card-body">', // card-body opens here`  [:- so card body is a *div*]
`'after_widget'  => '<div></section>', // card-body and card closes here` [:- card is closed by the tag `</section>`. But which opening tag closes the **`<div>`** in line `after_widget...`? **None! It itself is opening a tag!!!**

I had already understood what you described above. What I did not understand is this opening *div* just before the closing `*</section>*`

Your comments show, that you wanted to write  `'</div></section>'` instead of `'<div></section>'`. Is it a typo?

If yes: The more untitled widgets you have in the sidebar, the more superfluous closing **`</div>`** you have.
If no: The more untitled widgets you have in the sidebar, the more superfluous opening / unclosed **`</div>`** you have.

heartfully KR

**Comment by crftwrk** [comment] 2023-04-10 07:59
You're right! This should be `</div></section>`. Thank you for figuring this out.

**Comment by kreincke** [comment] 2023-04-10 16:57
After having played with this function I now know that there isn't a solution for what I want. To define it properly, we would need a context sensitive grammar, which can not been realized by before-xy and after-xy. Instead of that, we could embed the whole section in a div marked with `class="card-body"`. By this, every widget gets a border. But it's not as elegant as your style: also the headline inherits the paddings. Therefore I decided to take your code as it is. The consequence for me - and also for your other users - is this:

* If you insert a widget that should be titled and has a title option, then everything is fine.
* If you insert a widget that should not be titled
  * If the widget allows being edited as HTML -code, 
    * do not insert a title on the widget level
    * insert a surrounding `<div class="card-body">[...]</div>`
  * If the widget does not allow to be edited as HTML -code (like e.g. the standard image widget, or the well-known WP plugin *Recent Posts Widget With Thumbnails*)
    * replace the widget with an alternative (in the case of images: take the text widget and insert the image into it
    * use a headline even if it is not necessary
 
I will document this in an article. For me this way acceptable, because most sidebar units, which do not need a title, are probably not so often modified. Unfortunately, I can't demo it, because I have another issue with release 5.2.3.3 which I have to solve first. (I will send an extra desciprtion, so, that we can close this issue really).

**Comment by kreincke** [comment] 2023-04-11 07:25
nice idea! I will check it during the next days. heartfully KR

**Comment by kreincke** [comment] 2023-04-14 14:29
After having modified the function in bootscore-main and added the respective css in my bs_customer.css, I can confirm, that it works! Many thanks. I like to have both options: to use sidebar cards (sometimes created by plugins) with and without a title. 

And this new version creates a much cleaner HTML code.

Thanks!! I am looking forward for getting 5.3.0. Do you already know when it will be released?

br KR

**Comment by kreincke** [comment] 2023-04-14 14:56
And now you can see these improvements in a live system: [https://fodina.de/](https://fodina.de/):
* the top widget is a pure unmodified *wp image widget* embedding an svg
* the middle widget is a widget with a title
* the bottom widget is a text widget without a title.

Looks great!

**Comment by crftwrk** [comment] 2023-04-15 10:05
> ...5.3.0. Do you already know when it will be released?

We do not have to wait until 5.3, we can ship a quick patch when merged.

**Comment by kreincke** [comment] 2023-04-15 10:56
Wonderful! Great service!!

**Closed** 2023-04-15 14:59 UTC
