### ISSUE TITLE
The filemtime() function in PHP cannot handle Windows paths

### ISSUE THREAD

**Issue by amandato** [bootscore/bootscore#540] opened 2023-08-07 02:15 UTC
Getting the following error:
```Warning: filemtime(): stat failed for C:\...\wp/wp-content//themes/bootscore-child-main/css/main.css in C:\...\wp\wp-content\themes\bootscore-child-main\functions.php on line 11```

The filemtime() function in PHP cannot handle Windows paths with the double slashes in the path. Simple fix, on line 11 add the wp_normalize_path() function.

Change line 11 from:
`$modified_bootscoreChildCss = date('YmdHi', filemtime(get_stylesheet_directory() . '/css/main.css'));`

to:
`$modified_bootscoreChildCss = date('YmdHi', filemtime( wp_normalize_path(get_stylesheet_directory() . '/css/main.css')));`

Thanks for an awesome theme!

**Comment by crftwrk** [comment] 2023-08-07 09:55
Thank you for reporting. Moved this issue to main-theme repo because this have to be changed here as well: 

https://github.com/bootscore/bootscore/blob/3351cbe1ad9201d518b8432e283d02e54e9747a8/functions.php#L259-L264

Want to quickly create a pull request?

**Comment by crftwrk** [comment] 2023-11-12 13:48
I cannot reproduce this issue and there was no user feedback. I close this issue now.

**Closed by crftwrk** 2023-11-12 13:48 UTC
Labels: bug, child
