### ISSUE TITLE
Main.css version not updating

### ISSUE THREAD

**Issue by jamessilverstripe** [bootscore/bootscore#877] opened 2024-11-18 07:38 UTC
### Discussed in https://github.com/orgs/bootscore/discussions/876

<div type='discussions-op-text'>

<sup>Originally posted by **jamessilverstripe** November 18, 2024</sup>
I've recently started using the latest version of Bootscore and have encountered an issue I've not had with previous versions. The main.css file is compiling and updating correctly but the version number in the head is set to "?ver=6.0.0". If I change the ver number or remove it completely, the correct styles load. I have turned off my cache, tried deleting main.css, have tried dev mode in wp config but nothing is working. Please help 🙏 </div>

**Comment by crftwrk** [comment] 2024-11-18 14:34
Hm, that's strange. Tested it on parent- and child-theme and `main.css` version works as expected with added new version on each compile with `year/month/day/time` `main.css?ver=202411181417`?

Do you have a link to your site? Versioning of enqueued `main.css` happens here:

#### Bootscore

https://github.com/bootscore/bootscore/blob/4e37a62324f616850d53a5998d25a57743cd9d64/inc/enqueue.php#L21

https://github.com/bootscore/bootscore/blob/4e37a62324f616850d53a5998d25a57743cd9d64/inc/enqueue.php#L27-L30

#### Bootscore Child

https://github.com/bootscore/bootscore-child/blob/0037462f407ae6694290a2f17e3ff2c5f2edde93/functions.php#L20-L22

```php
  // Compiled main.css
  $modified_bootscoreChildCss = date('YmdHi', filemtime(get_stylesheet_directory() . '/assets/css/main.css'));
  wp_enqueue_style('main', get_stylesheet_directory_uri() . '/assets/css/main.css', array('parent-style'), $modified_bootscoreChildCss);
```

**Comment by crftwrk** [comment] 2024-12-09 10:22
Haven't received any feedback here and can't reproduce the issue, so I'm closing the issue now.

**Closed by crftwrk** 2024-12-09 10:22 UTC
