### ISSUE TITLE
[BUG] Not able to scroll page using Divi page editor on Tab and Mobile view

### ISSUE THREAD

**Issue by gurpreetbhachu** [bootscore/bootscore#656] opened 2023-12-15 05:06 UTC
### Describe the bug

I don't know if Bootscore is compatible with DIVI page builder.
Issue I am facing is I am not able to scroll the page when editing the page on Tab and Mobile view.
Everything is working fine on wordpress default themes.
![Divi1](https://github.com/bootscore/bootscore/assets/35268356/f08a0ac2-08b2-4741-8c12-e8f21d00c68c)

### Steps to reproduce

1. Activate Divi builder.
2. Edit using visual builder.
3. Switch to Tab/Mobile view
4. Try to scroll

**Comment by crftwrk** [comment] 2023-12-15 11:43
Hello,

theme is not tested with Divi builder and we do not have this plugin. Bug reports must have a link to reproduce the issue. Please install a test page and share a link to it.

**Comment by justinkruit** [comment] 2023-12-15 16:39
You'll be able to share your credentials using the following URL with the bootScore team. https://bootscore.me/private-info-form/

**Comment by gurpreetbhachu** [comment] 2023-12-15 16:49
Information Submitted :)

1. Login
2. Go to Homepage.
3. On Admin bar > Click "Enable Visual Builder".
4. Click on the Three dots at the bottom center.
5. Select Different view from the Bottom Left options.
6. Try to scroll page after setting it to Tab or Mobile view.

Let me know if you have any questions.

**Comment by crftwrk** [comment] 2023-12-15 17:27
Divi adds some inline-styles overflow hidden to `<html>` and `<body>` depending on the screen size. Add following snippet to your SCSS and let me know if that helps. I can't do it because theme editor is blocked for me.

```css
#page {
  overflow-y: scroll !important;
}
```

**Comment by gurpreetbhachu** [comment] 2023-12-15 18:03
Yippiee!! that worked 👍 

Heartfelt Thanks for the Fix and Admiration for Bootscore!

I wanted to express my sincere gratitude for the fantastic solution you provided to fix the issue. Your expertise and quick response have been invaluable, and I am truly thankful for your assistance.

On another note, I wanted to let you know how much I love the "**Bootscore**" Its design and user-friendly features , and I am thoroughly impressed with its performance.

Once again, thank you for your outstanding support and for contributing to the success of my online presence. Your dedication to creating and maintaining such a wonderful theme is truly commendable. :)

You are the best :)

Best regards,
Gurpreet Singh
Toronto, Canada

**Comment by crftwrk** [comment] 2023-12-19 09:22
Thank you! Close this issue as completed now.

**Closed by crftwrk** 2023-12-19 09:22 UTC
Labels: bug
